# Standards: 1.1.37
---

# 1.2.2 Ensure GPG keys are configured

# The remediation actions for this recommendation are site-specific, therefore we test that
# executing the specified rpm command results in no errors.
- name: 1.2.2 - Ensure GPG keys are configured
  command: apt-key list
  register: apt_key_list
  changed_when: false
  args:
    warn: false
  tags:
    - level-1
    - "1.2.2"
    - scored
    - skip_ansible_lint
