# Standards: 1.1.38
---

# 1.5.4 Ensure prelink is disabled

- name: 1.5.4 - Check if prelink is installed
  shell: "dpkg -l | grep prelink | cut -d' ' -f1"  
  register: pkg
  tags:
    - level-1
    - "1.5.4"
    - scored
    - skip_ansible_lint

- name: 1.5.4 - Display the registered package
  debug:
    msg: Value equals {{ pkg.stdout_lines }} 
  when: pkg.stdout == "ii"
  tags:
    - level-1
    - "1.5.4"
    - scored
    - skip_ansible_lint

- name: 1.5.4 - Restore prelinked binaries
  command: prelink -ua
  when: pkg.stdout == "ii"
  tags:
    - level-1
    - "1.5.4"
    - scored
    - skip_ansible_lint

- name: 1.5.4 - Ensure prelink is disabled
  apt:
    name: prelink
    state: absent
  when: pkg.stdout == "ii"
  tags:
    - level-1
    - "1.5.4"
    - scored
